from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

from monster.feature_compile.mechanisms import (
    PlayerMechanismInputs,
    TeamMechanismInputs,
)
from monster.registry import FeatureRegistry
from monster.sim.allocation import GameAllocationWorlds, allocate_game_players
from monster.sim.game import GameWorlds, simulate_game
from monster.snapshot.compile import CompiledGameSnapshot, compile_game_snapshot
from monster.snapshot.model import GameState
from monster.snapshot.player import TeamPlayerPool


@dataclass(frozen=True)
class MonsterGameWorlds:
    snapshot: CompiledGameSnapshot
    game_worlds: GameWorlds
    allocation_worlds: GameAllocationWorlds


def simulate_monster_game(
    game: GameState,
    away_pool: TeamPlayerPool,
    home_pool: TeamPlayerPool,
    *,
    worlds: int,
    seed: int,
    away_team_inputs: TeamMechanismInputs | None = None,
    home_team_inputs: TeamMechanismInputs | None = None,
    player_inputs: Mapping[str, PlayerMechanismInputs] | None = None,
    registry: FeatureRegistry | None = None,
) -> MonsterGameWorlds:
    """Compile rich football evidence, simulate scoring, then allocate that supply.

    This is the canonical single-game execution order. Player allocation never creates
    a separate scoring universe; it consumes the touchdowns, drives and points already
    generated by the market-blind game simulation.
    """
    snapshot = compile_game_snapshot(
        game,
        away_pool,
        home_pool,
        away_team_inputs=away_team_inputs,
        home_team_inputs=home_team_inputs,
        player_inputs=player_inputs,
        registry=registry,
    )
    game_worlds = simulate_game(snapshot.game, worlds=worlds, seed=seed)
    allocation_worlds = allocate_game_players(
        game_worlds,
        snapshot.away_pool,
        snapshot.home_pool,
        seed=seed + 1_000_003,
    )
    return MonsterGameWorlds(
        snapshot=snapshot,
        game_worlds=game_worlds,
        allocation_worlds=allocation_worlds,
    )
